/**
 * Comprehensive Interests Seed Data
 * Based on updated taxonomy for male bonding and ministry formation
 *
 * Categories:
 * 1. outdoor_adventure
 * 2. craftsmanship_trades_maker
 * 3. physicality_combat_team_sports
 * 4. culinary_fire_food
 * 5. strategy_mentorship_leadership
 * 6. faith_formation_relational
 * 7. service_civic_community
 * 8. creative_cultural
 * 9. digital_tech
 *
 * Metadata fields:
 * - intensity: "low" | "medium" | "high"
 * - commitment: "one_off" | "recurring" | "program" (8+ weeks)
 * - location: "indoor" | "outdoor" | "hybrid" | "travel"
 * - skillLevel: "beginner" | "intermediate" | "advanced" | "instructor"
 * - trustRequirement: "open" | "vouched" | "verified_leader"
 * - safety: "required" | "recommended" | "none"
 * - spiritualFocus: "social" | "service" | "discipleship" | "worship" | null
 */

export const interests = [
  // ========================================
  // 1. OUTDOOR & ADVENTURE
  // ========================================
  {
    name: 'Hunting & Fishing',
    category: 'outdoor_adventure',
    description: 'Hunting, fishing, conservation ethics, safety training',
    popularity: 70,
    metadata: {
      intensity: 'medium',
      commitment: 'recurring',
      location: 'outdoor',
      skillLevel: 'intermediate',
      trustRequirement: 'vouched',
      safety: 'required',
      spiritualFocus: null,
    },
  },
  {
    name: 'Trail Running & Endurance Events',
    category: 'outdoor_adventure',
    description: 'Trail running, ultra marathons, obstacle races',
    popularity: 75,
    metadata: {
      intensity: 'high',
      commitment: 'recurring',
      location: 'outdoor',
      skillLevel: 'intermediate',
      trustRequirement: 'open',
      safety: 'recommended',
      spiritualFocus: null,
    },
  },
  {
    name: 'Camping & Bushcraft',
    category: 'outdoor_adventure',
    description: 'Camping, bushcraft, survival skills',
    popularity: 80,
    metadata: {
      intensity: 'medium',
      commitment: 'recurring',
      location: 'outdoor',
      skillLevel: 'beginner',
      trustRequirement: 'open',
      safety: 'recommended',
      spiritualFocus: null,
    },
  },
  {
    name: 'Mountaineering & Alpinism',
    category: 'outdoor_adventure',
    description: 'Mountain climbing, alpine adventures',
    popularity: 60,
    metadata: {
      intensity: 'high',
      commitment: 'recurring',
      location: 'outdoor',
      skillLevel: 'advanced',
      trustRequirement: 'verified_leader',
      safety: 'required',
      spiritualFocus: null,
    },
  },
  {
    name: 'Overlanding & Off-roading',
    category: 'outdoor_adventure',
    description: '4x4 adventures, vehicle-based camping',
    popularity: 68,
    metadata: {
      intensity: 'medium',
      commitment: 'recurring',
      location: 'outdoor',
      skillLevel: 'intermediate',
      trustRequirement: 'open',
      safety: 'recommended',
      spiritualFocus: null,
    },
  },
  {
    name: 'Sailing & Boating',
    category: 'outdoor_adventure',
    description: 'Sailing, powerboating, water sports',
    popularity: 55,
    metadata: {
      intensity: 'medium',
      commitment: 'recurring',
      location: 'outdoor',
      skillLevel: 'intermediate',
      trustRequirement: 'open',
      safety: 'required',
      spiritualFocus: null,
    },
  },
  {
    name: 'Wilderness First Aid',
    category: 'outdoor_adventure',
    description: 'Emergency response in remote settings',
    popularity: 65,
    metadata: {
      intensity: 'medium',
      commitment: 'program',
      location: 'hybrid',
      skillLevel: 'instructor',
      trustRequirement: 'verified_leader',
      safety: 'required',
      spiritualFocus: null,
    },
  },
  {
    name: 'Navigation & Orienteering',
    category: 'outdoor_adventure',
    description: 'Map, compass, GPS skills',
    popularity: 58,
    metadata: {
      intensity: 'low',
      commitment: 'recurring',
      location: 'outdoor',
      skillLevel: 'beginner',
      trustRequirement: 'open',
      safety: 'recommended',
      spiritualFocus: null,
    },
  },
  {
    name: 'Hiking & Backpacking',
    category: 'outdoor_adventure',
    description: 'Day hikes, multi-day backpacking trips',
    popularity: 85,
    metadata: {
      intensity: 'medium',
      commitment: 'recurring',
      location: 'outdoor',
      skillLevel: 'beginner',
      trustRequirement: 'open',
      safety: 'recommended',
      spiritualFocus: null,
    },
  },
  {
    name: 'Rock Climbing & Bouldering',
    category: 'outdoor_adventure',
    description: 'Indoor/outdoor climbing, bouldering',
    popularity: 70,
    metadata: {
      intensity: 'high',
      commitment: 'recurring',
      location: 'hybrid',
      skillLevel: 'intermediate',
      trustRequirement: 'open',
      safety: 'required',
      spiritualFocus: null,
    },
  },

  // ========================================
  // 2. CRAFTSMANSHIP, TRADES & MAKER
  // ========================================
  {
    name: 'Woodworking & Carpentry',
    category: 'craftsmanship_trades_maker',
    description: 'Furniture making, woodworking projects',
    popularity: 75,
    metadata: {
      intensity: 'medium',
      commitment: 'recurring',
      location: 'indoor',
      skillLevel: 'intermediate',
      trustRequirement: 'open',
      safety: 'recommended',
      spiritualFocus: null,
    },
  },
  {
    name: 'Metalworking & Blacksmithing',
    category: 'craftsmanship_trades_maker',
    description: 'Forging, welding, metal fabrication',
    popularity: 65,
    metadata: {
      intensity: 'high',
      commitment: 'recurring',
      location: 'indoor',
      skillLevel: 'advanced',
      trustRequirement: 'vouched',
      safety: 'required',
      spiritualFocus: null,
    },
  },
  {
    name: 'Automotive Restoration',
    category: 'craftsmanship_trades_maker',
    description: 'Classic car restoration, mechanics',
    popularity: 68,
    metadata: {
      intensity: 'medium',
      commitment: 'program',
      location: 'indoor',
      skillLevel: 'intermediate',
      trustRequirement: 'open',
      safety: 'recommended',
      spiritualFocus: null,
    },
  },
  {
    name: 'Home Renovation & Repair',
    category: 'craftsmanship_trades_maker',
    description: 'DIY home projects, repairs, construction',
    popularity: 78,
    metadata: {
      intensity: 'medium',
      commitment: 'recurring',
      location: 'hybrid',
      skillLevel: 'beginner',
      trustRequirement: 'open',
      safety: 'recommended',
      spiritualFocus: null,
    },
  },
  {
    name: 'Brewing & Distilling',
    category: 'craftsmanship_trades_maker',
    description: 'Homebrewing beer, wine, spirits',
    popularity: 62,
    metadata: {
      intensity: 'low',
      commitment: 'recurring',
      location: 'indoor',
      skillLevel: 'beginner',
      trustRequirement: 'open',
      safety: 'none',
      spiritualFocus: null,
    },
  },
  {
    name: 'Leatherworking',
    category: 'craftsmanship_trades_maker',
    description: 'Leather crafts, tool making, bags, belts',
    popularity: 58,
    metadata: {
      intensity: 'low',
      commitment: 'recurring',
      location: 'indoor',
      skillLevel: 'beginner',
      trustRequirement: 'open',
      safety: 'none',
      spiritualFocus: null,
    },
  },
  {
    name: 'Gardening & Homesteading',
    category: 'craftsmanship_trades_maker',
    description: 'Vegetable gardens, small-scale farming, chickens',
    popularity: 72,
    metadata: {
      intensity: 'medium',
      commitment: 'recurring',
      location: 'outdoor',
      skillLevel: 'beginner',
      trustRequirement: 'open',
      safety: 'none',
      spiritualFocus: null,
    },
  },
  {
    name: 'Small Business & Trade Mentoring',
    category: 'craftsmanship_trades_maker',
    description: 'Mentoring apprentices, sharing trade skills',
    popularity: 60,
    metadata: {
      intensity: 'low',
      commitment: 'program',
      location: 'hybrid',
      skillLevel: 'instructor',
      trustRequirement: 'verified_leader',
      safety: 'none',
      spiritualFocus: 'service',
    },
  },

  // ========================================
  // 3. PHYSICALITY, COMBAT & TEAM SPORTS
  // ========================================
  {
    name: 'Martial Arts & Combat Sports',
    category: 'physicality_combat_team_sports',
    description: 'BJJ, Muay Thai, boxing, Krav Maga',
    popularity: 75,
    metadata: {
      intensity: 'high',
      commitment: 'recurring',
      location: 'indoor',
      skillLevel: 'intermediate',
      trustRequirement: 'open',
      safety: 'recommended',
      spiritualFocus: null,
    },
  },
  {
    name: 'Strength Training & Weightlifting',
    category: 'physicality_combat_team_sports',
    description: 'Powerlifting, Olympic lifting, bodybuilding',
    popularity: 88,
    metadata: {
      intensity: 'high',
      commitment: 'recurring',
      location: 'indoor',
      skillLevel: 'beginner',
      trustRequirement: 'open',
      safety: 'recommended',
      spiritualFocus: null,
    },
  },
  {
    name: 'Competitive Team Sports',
    category: 'physicality_combat_team_sports',
    description: 'Soccer, rugby, hockey, lacrosse - organized leagues, structured teams, regular practices',
    popularity: 70,
    metadata: {
      intensity: 'high',
      commitment: 'recurring',
      location: 'outdoor',
      skillLevel: 'beginner',
      trustRequirement: 'open',
      safety: 'recommended',
      spiritualFocus: null,
    },
  },
  {
    name: 'Marksmanship & Archery',
    category: 'physicality_combat_team_sports',
    description: 'Firearms training, archery, competitive shooting',
    popularity: 65,
    metadata: {
      intensity: 'medium',
      commitment: 'recurring',
      location: 'outdoor',
      skillLevel: 'intermediate',
      trustRequirement: 'vouched',
      safety: 'required',
      spiritualFocus: null,
    },
  },
  {
    name: 'Endurance Running & Obstacle Races',
    category: 'physicality_combat_team_sports',
    description: 'Marathons, Spartan races, tough mudders',
    popularity: 72,
    metadata: {
      intensity: 'high',
      commitment: 'recurring',
      location: 'outdoor',
      skillLevel: 'intermediate',
      trustRequirement: 'open',
      safety: 'recommended',
      spiritualFocus: null,
    },
  },
  {
    name: 'Motorcycling & Touring',
    category: 'physicality_combat_team_sports',
    description: 'Motorcycle riding, touring, safety training',
    popularity: 68,
    metadata: {
      intensity: 'medium',
      commitment: 'recurring',
      location: 'outdoor',
      skillLevel: 'intermediate',
      trustRequirement: 'open',
      safety: 'required',
      spiritualFocus: null,
    },
  },
  {
    name: 'CrossFit & Functional Fitness',
    category: 'physicality_combat_team_sports',
    description: 'High-intensity functional training',
    popularity: 80,
    metadata: {
      intensity: 'high',
      commitment: 'recurring',
      location: 'indoor',
      skillLevel: 'beginner',
      trustRequirement: 'open',
      safety: 'recommended',
      spiritualFocus: null,
    },
  },

  // ========================================
  // 4. CULINARY, FIRE & FOOD SYSTEMS
  // ========================================
  {
    name: 'Barbecue & Grilling',
    category: 'culinary_fire_food',
    description: 'Smoking meat, grilling, BBQ competitions',
    popularity: 82,
    metadata: {
      intensity: 'low',
      commitment: 'recurring',
      location: 'outdoor',
      skillLevel: 'beginner',
      trustRequirement: 'open',
      safety: 'none',
      spiritualFocus: null,
    },
  },
  {
    name: 'Butchery & Meat Processing',
    category: 'culinary_fire_food',
    description: 'Whole animal butchery, charcuterie',
    popularity: 58,
    metadata: {
      intensity: 'medium',
      commitment: 'program',
      location: 'indoor',
      skillLevel: 'advanced',
      trustRequirement: 'vouched',
      safety: 'required',
      spiritualFocus: null,
    },
  },
  {
    name: 'Foraging & Wild Foods',
    category: 'culinary_fire_food',
    description: 'Wild edible plants, mushrooms, ethical harvesting',
    popularity: 62,
    metadata: {
      intensity: 'low',
      commitment: 'recurring',
      location: 'outdoor',
      skillLevel: 'intermediate',
      trustRequirement: 'open',
      safety: 'recommended',
      spiritualFocus: null,
    },
  },
  {
    name: 'Cooking & Culinary Arts',
    category: 'culinary_fire_food',
    description: 'Home cooking, knife skills, recipe development',
    popularity: 75,
    metadata: {
      intensity: 'low',
      commitment: 'recurring',
      location: 'indoor',
      skillLevel: 'beginner',
      trustRequirement: 'open',
      safety: 'none',
      spiritualFocus: null,
    },
  },
  {
    name: 'Community Kitchens & Food Service',
    category: 'culinary_fire_food',
    description: 'Feeding the hungry, meal prep outreach',
    popularity: 70,
    metadata: {
      intensity: 'medium',
      commitment: 'recurring',
      location: 'indoor',
      skillLevel: 'beginner',
      trustRequirement: 'open',
      safety: 'none',
      spiritualFocus: 'service',
    },
  },

  // ========================================
  // 5. STRATEGY, MENTORSHIP & LEADERSHIP
  // ========================================
  {
    name: 'Chess & Strategy Games',
    category: 'strategy_mentorship_leadership',
    description: 'Chess, board games, strategic thinking',
    popularity: 68,
    metadata: {
      intensity: 'low',
      commitment: 'recurring',
      location: 'indoor',
      skillLevel: 'beginner',
      trustRequirement: 'open',
      safety: 'none',
      spiritualFocus: null,
    },
  },
  {
    name: 'Mentorship & Coaching',
    category: 'strategy_mentorship_leadership',
    description: 'One-on-one mentoring, life coaching',
    popularity: 75,
    metadata: {
      intensity: 'medium',
      commitment: 'program',
      location: 'hybrid',
      skillLevel: 'instructor',
      trustRequirement: 'verified_leader',
      safety: 'none',
      spiritualFocus: 'service',
    },
  },
  {
    name: 'Leadership Training',
    category: 'strategy_mentorship_leadership',
    description: 'Team leadership, servant leadership, facilitation',
    popularity: 72,
    metadata: {
      intensity: 'medium',
      commitment: 'program',
      location: 'hybrid',
      skillLevel: 'intermediate',
      trustRequirement: 'verified_leader',
      safety: 'none',
      spiritualFocus: 'discipleship',
    },
  },
  {
    name: 'Entrepreneurship & Startups',
    category: 'strategy_mentorship_leadership',
    description: 'Building businesses, product development',
    popularity: 78,
    metadata: {
      intensity: 'high',
      commitment: 'program',
      location: 'hybrid',
      skillLevel: 'intermediate',
      trustRequirement: 'open',
      safety: 'none',
      spiritualFocus: null,
    },
  },
  {
    name: 'Project Leadership & Service',
    category: 'strategy_mentorship_leadership',
    description: 'Leading volunteer projects, coordinating teams',
    popularity: 65,
    metadata: {
      intensity: 'medium',
      commitment: 'recurring',
      location: 'hybrid',
      skillLevel: 'intermediate',
      trustRequirement: 'vouched',
      safety: 'none',
      spiritualFocus: 'service',
    },
  },
  {
    name: 'Financial Stewardship & Personal Finance',
    category: 'strategy_mentorship_leadership',
    description: 'Budgeting, investing, financial coaching',
    popularity: 70,
    metadata: {
      intensity: 'low',
      commitment: 'program',
      location: 'hybrid',
      skillLevel: 'intermediate',
      trustRequirement: 'open',
      safety: 'none',
      spiritualFocus: null,
    },
  },

  // ========================================
  // 6. FAITH, FORMATION & RELATIONAL CARE
  // ========================================
  {
    name: 'Bible Study & Scripture',
    category: 'faith_formation_relational',
    description: 'Group Bible study, inductive study, theology',
    popularity: 85,
    metadata: {
      intensity: 'low',
      commitment: 'recurring',
      location: 'hybrid',
      skillLevel: 'beginner',
      trustRequirement: 'open',
      safety: 'none',
      spiritualFocus: 'discipleship',
    },
  },
  {
    name: 'Prayer Cohorts & Intercession',
    category: 'faith_formation_relational',
    description: 'Prayer groups, prayer walking, intercession',
    popularity: 80,
    metadata: {
      intensity: 'low',
      commitment: 'recurring',
      location: 'hybrid',
      skillLevel: 'beginner',
      trustRequirement: 'open',
      safety: 'none',
      spiritualFocus: 'worship',
    },
  },
  {
    name: 'Spiritual Retreats & Solitude',
    category: 'faith_formation_relational',
    description: 'Quiet days, silent retreats, Sabbath rest',
    popularity: 68,
    metadata: {
      intensity: 'low',
      commitment: 'one_off',
      location: 'hybrid',
      skillLevel: 'beginner',
      trustRequirement: 'open',
      safety: 'none',
      spiritualFocus: 'worship',
    },
  },
  {
    name: 'Spiritual Mentoring & Direction',
    category: 'faith_formation_relational',
    description: 'Spiritual direction, faith mentoring',
    popularity: 72,
    metadata: {
      intensity: 'medium',
      commitment: 'program',
      location: 'hybrid',
      skillLevel: 'instructor',
      trustRequirement: 'verified_leader',
      safety: 'none',
      spiritualFocus: 'discipleship',
    },
  },
  {
    name: 'Parenting & Fathering Groups',
    category: 'faith_formation_relational',
    description: 'Dad cohorts, fathering workshops, parenting skills',
    popularity: 78,
    metadata: {
      intensity: 'medium',
      commitment: 'program',
      location: 'hybrid',
      skillLevel: 'beginner',
      trustRequirement: 'open',
      safety: 'none',
      spiritualFocus: 'discipleship',
    },
  },
  {
    name: 'Pastoral Peer Support',
    category: 'faith_formation_relational',
    description: 'Ministry leader support, pastor cohorts',
    popularity: 65,
    metadata: {
      intensity: 'medium',
      commitment: 'recurring',
      location: 'hybrid',
      skillLevel: 'advanced',
      trustRequirement: 'verified_leader',
      safety: 'none',
      spiritualFocus: 'discipleship',
    },
  },
  {
    name: 'Mental Health Peer Support',
    category: 'faith_formation_relational',
    description: 'Resilience groups, mental health advocacy',
    popularity: 70,
    metadata: {
      intensity: 'medium',
      commitment: 'recurring',
      location: 'hybrid',
      skillLevel: 'intermediate',
      trustRequirement: 'verified_leader',
      safety: 'recommended',
      spiritualFocus: 'service',
    },
  },
  {
    name: 'Liturgical Practices & Rhythms',
    category: 'faith_formation_relational',
    description: 'Daily office, liturgy, sacred rhythms',
    popularity: 62,
    metadata: {
      intensity: 'low',
      commitment: 'recurring',
      location: 'hybrid',
      skillLevel: 'beginner',
      trustRequirement: 'open',
      safety: 'none',
      spiritualFocus: 'worship',
    },
  },

  // ========================================
  // 7. SERVICE, CIVIC & COMMUNITY ACTION
  // ========================================
  {
    name: 'Volunteer Builds (Habitat, Disaster Relief)',
    category: 'service_civic_community',
    description: 'Construction projects, disaster response, rebuilding',
    popularity: 75,
    metadata: {
      intensity: 'high',
      commitment: 'recurring',
      location: 'outdoor',
      skillLevel: 'beginner',
      trustRequirement: 'open',
      safety: 'recommended',
      spiritualFocus: 'service',
    },
  },
  {
    name: 'Community Outreach & Street Ministry',
    category: 'service_civic_community',
    description: 'Homeless outreach, street ministry, compassion work',
    popularity: 72,
    metadata: {
      intensity: 'medium',
      commitment: 'recurring',
      location: 'outdoor',
      skillLevel: 'beginner',
      trustRequirement: 'open',
      safety: 'recommended',
      spiritualFocus: 'service',
    },
  },
  {
    name: 'Prison Ministry & Re-entry Support',
    category: 'service_civic_community',
    description: 'Jail ministry, re-entry mentoring, advocacy',
    popularity: 60,
    metadata: {
      intensity: 'medium',
      commitment: 'program',
      location: 'hybrid',
      skillLevel: 'intermediate',
      trustRequirement: 'verified_leader',
      safety: 'required',
      spiritualFocus: 'service',
    },
  },
  {
    name: 'Veterans Support & Advocacy',
    category: 'service_civic_community',
    description: 'Veteran peer groups, transition support',
    popularity: 68,
    metadata: {
      intensity: 'medium',
      commitment: 'recurring',
      location: 'hybrid',
      skillLevel: 'intermediate',
      trustRequirement: 'vouched',
      safety: 'recommended',
      spiritualFocus: 'service',
    },
  },
  {
    name: 'Civic Engagement & Advocacy',
    category: 'service_civic_community',
    description: 'Local politics, community organizing, justice work',
    popularity: 65,
    metadata: {
      intensity: 'medium',
      commitment: 'recurring',
      location: 'hybrid',
      skillLevel: 'intermediate',
      trustRequirement: 'open',
      safety: 'none',
      spiritualFocus: 'service',
    },
  },
  {
    name: 'Environmental Conservation',
    category: 'service_civic_community',
    description: 'Trail maintenance, habitat restoration, conservation',
    popularity: 70,
    metadata: {
      intensity: 'medium',
      commitment: 'recurring',
      location: 'outdoor',
      skillLevel: 'beginner',
      trustRequirement: 'open',
      safety: 'recommended',
      spiritualFocus: 'service',
    },
  },

  // ========================================
  // 8. CREATIVE & CULTURAL
  // ========================================
  {
    name: 'Music & Worship Teams',
    category: 'creative_cultural',
    description: 'Playing instruments, leading worship, songwriting',
    popularity: 78,
    metadata: {
      intensity: 'medium',
      commitment: 'recurring',
      location: 'indoor',
      skillLevel: 'intermediate',
      trustRequirement: 'open',
      safety: 'none',
      spiritualFocus: 'worship',
    },
  },
  {
    name: 'Storytelling & Testimony',
    category: 'creative_cultural',
    description: 'Sharing stories, testimony nights, oral tradition',
    popularity: 72,
    metadata: {
      intensity: 'low',
      commitment: 'recurring',
      location: 'indoor',
      skillLevel: 'beginner',
      trustRequirement: 'open',
      safety: 'none',
      spiritualFocus: 'discipleship',
    },
  },
  {
    name: 'Film & Photography',
    category: 'creative_cultural',
    description: 'Photography outings, filmmaking, visual storytelling',
    popularity: 75,
    metadata: {
      intensity: 'low',
      commitment: 'recurring',
      location: 'hybrid',
      skillLevel: 'intermediate',
      trustRequirement: 'open',
      safety: 'none',
      spiritualFocus: null,
    },
  },
  {
    name: 'Craft Circles (Leatherwork, Instruments)',
    category: 'creative_cultural',
    description: 'Craft groups, instrument building, traditional skills',
    popularity: 60,
    metadata: {
      intensity: 'low',
      commitment: 'recurring',
      location: 'indoor',
      skillLevel: 'beginner',
      trustRequirement: 'open',
      safety: 'none',
      spiritualFocus: null,
    },
  },
  {
    name: 'Theater & Performance Arts',
    category: 'creative_cultural',
    description: 'Acting, improv, drama ministry',
    popularity: 58,
    metadata: {
      intensity: 'medium',
      commitment: 'program',
      location: 'indoor',
      skillLevel: 'beginner',
      trustRequirement: 'open',
      safety: 'none',
      spiritualFocus: 'worship',
    },
  },
  {
    name: 'Writing & Journaling',
    category: 'creative_cultural',
    description: 'Creative writing, blogging, reflective journaling',
    popularity: 68,
    metadata: {
      intensity: 'low',
      commitment: 'recurring',
      location: 'hybrid',
      skillLevel: 'beginner',
      trustRequirement: 'open',
      safety: 'none',
      spiritualFocus: null,
    },
  },
  {
    name: 'Book Clubs & Literature',
    category: 'creative_cultural',
    description: 'Reading groups, theology books, literature discussion',
    popularity: 70,
    metadata: {
      intensity: 'low',
      commitment: 'recurring',
      location: 'indoor',
      skillLevel: 'beginner',
      trustRequirement: 'open',
      safety: 'none',
      spiritualFocus: 'discipleship',
    },
  },

  // ========================================
  // ADDITIONAL HIGH-ENGAGEMENT INTERESTS
  // ========================================
  {
    name: 'Skiing & Snowboarding',
    category: 'outdoor_adventure',
    description: 'Winter sports, backcountry skiing',
    popularity: 72,
    metadata: {
      intensity: 'high',
      commitment: 'recurring',
      location: 'outdoor',
      skillLevel: 'intermediate',
      trustRequirement: 'open',
      safety: 'recommended',
      spiritualFocus: null,
    },
  },
  {
    name: 'Surfing & Water Sports',
    category: 'outdoor_adventure',
    description: 'Surfing, paddleboarding, kayaking',
    popularity: 68,
    metadata: {
      intensity: 'medium',
      commitment: 'recurring',
      location: 'outdoor',
      skillLevel: 'intermediate',
      trustRequirement: 'open',
      safety: 'recommended',
      spiritualFocus: null,
    },
  },
  {
    name: 'Mountain Biking',
    category: 'outdoor_adventure',
    description: 'Trail riding, downhill, cross-country MTB',
    popularity: 75,
    metadata: {
      intensity: 'high',
      commitment: 'recurring',
      location: 'outdoor',
      skillLevel: 'intermediate',
      trustRequirement: 'open',
      safety: 'recommended',
      spiritualFocus: null,
    },
  },
  {
    name: 'Yoga & Mindfulness',
    category: 'physicality_combat_team_sports',
    description: 'Yoga practice, meditation, breathwork',
    popularity: 70,
    metadata: {
      intensity: 'low',
      commitment: 'recurring',
      location: 'hybrid',
      skillLevel: 'beginner',
      trustRequirement: 'open',
      safety: 'none',
      spiritualFocus: null,
    },
  },
  {
    name: 'Pickup & Casual Games',
    category: 'physicality_combat_team_sports',
    description: 'Basketball, volleyball, ultimate frisbee - drop-in games, low commitment, just show up and play',
    popularity: 72,
    metadata: {
      intensity: 'medium',
      commitment: 'recurring',
      location: 'outdoor',
      skillLevel: 'beginner',
      trustRequirement: 'open',
      safety: 'none',
      spiritualFocus: null,
    },
  },
  {
    name: 'Racquet & Paddle Sports',
    category: 'physicality_combat_team_sports',
    description: 'Tennis, badminton, table tennis, pickleball, squash, racquetball',
    popularity: 68,
    metadata: {
      intensity: 'medium',
      commitment: 'recurring',
      location: 'hybrid',
      skillLevel: 'beginner',
      trustRequirement: 'open',
      safety: 'none',
      spiritualFocus: null,
    },
  },
  {
    name: 'Golf & Disc Golf',
    category: 'physicality_combat_team_sports',
    description: 'Traditional golf, disc golf, recreational rounds',
    popularity: 65,
    metadata: {
      intensity: 'low',
      commitment: 'recurring',
      location: 'outdoor',
      skillLevel: 'beginner',
      trustRequirement: 'open',
      safety: 'none',
      spiritualFocus: null,
    },
  },
  {
    name: 'Coffee Roasting & Appreciation',
    category: 'culinary_fire_food',
    description: 'Home roasting, cupping, coffee culture',
    popularity: 68,
    metadata: {
      intensity: 'low',
      commitment: 'recurring',
      location: 'indoor',
      skillLevel: 'beginner',
      trustRequirement: 'open',
      safety: 'none',
      spiritualFocus: null,
    },
  },

  // ========================================
  // 9. DIGITAL & TECH
  // ========================================
  {
    name: 'Software Development',
    category: 'digital_tech',
    description: 'Web, mobile, backend development, full-stack engineering',
    popularity: 82,
    metadata: {
      intensity: 'medium',
      commitment: 'recurring',
      location: 'hybrid',
      skillLevel: 'intermediate',
      trustRequirement: 'open',
      safety: 'none',
      spiritualFocus: null,
    },
  },
  {
    name: 'Game Development',
    category: 'digital_tech',
    description: 'Unity, Unreal Engine, indie game creation',
    popularity: 65,
    metadata: {
      intensity: 'medium',
      commitment: 'recurring',
      location: 'indoor',
      skillLevel: 'intermediate',
      trustRequirement: 'open',
      safety: 'none',
      spiritualFocus: null,
    },
  },
  {
    name: 'DevOps & Cloud Engineering',
    category: 'digital_tech',
    description: 'AWS, Docker, Kubernetes, infrastructure, CI/CD pipelines',
    popularity: 70,
    metadata: {
      intensity: 'medium',
      commitment: 'recurring',
      location: 'hybrid',
      skillLevel: 'advanced',
      trustRequirement: 'open',
      safety: 'none',
      spiritualFocus: null,
    },
  },
  {
    name: 'Data Science & AI',
    category: 'digital_tech',
    description: 'Machine learning, data analysis, Python, AI models',
    popularity: 78,
    metadata: {
      intensity: 'medium',
      commitment: 'recurring',
      location: 'hybrid',
      skillLevel: 'advanced',
      trustRequirement: 'open',
      safety: 'none',
      spiritualFocus: null,
    },
  },
  {
    name: 'Cybersecurity',
    category: 'digital_tech',
    description: 'Ethical hacking, penetration testing, security research',
    popularity: 68,
    metadata: {
      intensity: 'medium',
      commitment: 'recurring',
      location: 'hybrid',
      skillLevel: 'advanced',
      trustRequirement: 'vouched',
      safety: 'recommended',
      spiritualFocus: null,
    },
  },
  {
    name: 'Open Source Contribution',
    category: 'digital_tech',
    description: 'GitHub projects, community coding, collaboration',
    popularity: 72,
    metadata: {
      intensity: 'low',
      commitment: 'recurring',
      location: 'hybrid',
      skillLevel: 'intermediate',
      trustRequirement: 'open',
      safety: 'none',
      spiritualFocus: 'service',
    },
  },
  {
    name: 'UI/UX Design',
    category: 'digital_tech',
    description: 'Figma, design systems, user experience, prototyping',
    popularity: 75,
    metadata: {
      intensity: 'low',
      commitment: 'recurring',
      location: 'hybrid',
      skillLevel: 'intermediate',
      trustRequirement: 'open',
      safety: 'none',
      spiritualFocus: null,
    },
  },
  {
    name: 'Video Editing & Production',
    category: 'digital_tech',
    description: 'Premiere, DaVinci Resolve, YouTube creation',
    popularity: 73,
    metadata: {
      intensity: 'medium',
      commitment: 'recurring',
      location: 'indoor',
      skillLevel: 'intermediate',
      trustRequirement: 'open',
      safety: 'none',
      spiritualFocus: null,
    },
  },
  {
    name: 'Digital Music Production',
    category: 'digital_tech',
    description: 'Ableton, Logic Pro, beat making, sound design',
    popularity: 68,
    metadata: {
      intensity: 'medium',
      commitment: 'recurring',
      location: 'indoor',
      skillLevel: 'intermediate',
      trustRequirement: 'open',
      safety: 'none',
      spiritualFocus: null,
    },
  },
  {
    name: 'Photography & Photo Editing',
    category: 'digital_tech',
    description: 'Lightroom, Photoshop, digital photography',
    popularity: 77,
    metadata: {
      intensity: 'low',
      commitment: 'recurring',
      location: 'hybrid',
      skillLevel: 'beginner',
      trustRequirement: 'open',
      safety: 'none',
      spiritualFocus: null,
    },
  },
  {
    name: 'Electronics & Maker Projects',
    category: 'digital_tech',
    description: 'Raspberry Pi, Arduino, IoT, home automation, robotics',
    popularity: 70,
    metadata: {
      intensity: 'medium',
      commitment: 'recurring',
      location: 'indoor',
      skillLevel: 'intermediate',
      trustRequirement: 'open',
      safety: 'none',
      spiritualFocus: null,
    },
  },
  {
    name: '3D Printing & CAD',
    category: 'digital_tech',
    description: '3D modeling, printing, prototyping, design',
    popularity: 66,
    metadata: {
      intensity: 'low',
      commitment: 'recurring',
      location: 'indoor',
      skillLevel: 'intermediate',
      trustRequirement: 'open',
      safety: 'none',
      spiritualFocus: null,
    },
  },
  {
    name: 'Raspberry Pi & Arduino',
    category: 'digital_tech',
    description: 'Embedded systems, microcontrollers, DIY electronics',
    popularity: 64,
    metadata: {
      intensity: 'low',
      commitment: 'recurring',
      location: 'indoor',
      skillLevel: 'intermediate',
      trustRequirement: 'open',
      safety: 'none',
      spiritualFocus: null,
    },
  },
  {
    name: 'Tech Blogging & Content Creation',
    category: 'digital_tech',
    description: 'Writing tutorials, tech reviews, podcasting',
    popularity: 69,
    metadata: {
      intensity: 'low',
      commitment: 'recurring',
      location: 'hybrid',
      skillLevel: 'beginner',
      trustRequirement: 'open',
      safety: 'none',
      spiritualFocus: null,
    },
  },
  {
    name: 'Crypto & Blockchain',
    category: 'digital_tech',
    description: 'Blockchain development, smart contracts, Web3',
    popularity: 62,
    metadata: {
      intensity: 'medium',
      commitment: 'recurring',
      location: 'hybrid',
      skillLevel: 'advanced',
      trustRequirement: 'open',
      safety: 'none',
      spiritualFocus: null,
    },
  },
];
